CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  `SIGLA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SISTEMA` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` TEXT NULL,
  `NOME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  `PASSWORD` TEXT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USUARIO_ROLE` (
  `USUARIO_ID` bigint(20) NOT NULL,
  `ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`,`ROLE_ID`),
  KEY `FK_8d9yu0x4s0up5dpjfedk93k3w` (`ROLE_ID`),
  CONSTRAINT `FK_8d9yu0x4s0up5dpjfedk93k3w` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`),
  CONSTRAINT `FK_fjubv3kj7l38pg1m6frl0lum1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `USUARIO_SISTEMA` (
	`USUARIO_ID` BIGINT(20) NOT NULL,
	`SISTEMA_ID` BIGINT(20) NOT NULL,
	PRIMARY KEY (`USUARIO_ID`, `SISTEMA_ID`),
	INDEX `FK_ai7q1diggesj4vkpl8a67n03o` (`SISTEMA_ID`),
	CONSTRAINT `FK_ld8lcc9iy02c11nl9lhonw0u0` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO` (`ID`),
	CONSTRAINT `FK_ai7q1diggesj4vkpl8a67n03o` FOREIGN KEY (`SISTEMA_ID`) REFERENCES `SISTEMA` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;


INSERT INTO `ROLE` (`ID`, `NOME`, `SIGLA`) VALUES (1, 'Administrador', 'ADM');
INSERT INTO `SISTEMA` (`ID`, `CLIENT_ID`, `NOME`) VALUES (1, '646514d85279c63c7aacbc7a91e7575bd2d1adcb0086c45840242b090c69cc08', 'Cliente Web');
INSERT INTO `USUARIO` (`ID`, `NOME`, `PASSWORD`, `USER_NAME`) VALUES (1, 'Teste', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'teste@teste.com');
INSERT INTO `USUARIO_ROLE` (`USUARIO_ID`, `ROLE_ID`) VALUES (1, 1);
INSERT INTO `USUARIO_SISTEMA` (`USUARIO_ID`, `SISTEMA_ID`) VALUES (1, 1);
