CREATE TABLE `USER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`LOGIN` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `UK_587tdsv8u5cvheyo9i261xhry` (`LOGIN`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4;


CREATE TABLE `ROLE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4;


CREATE TABLE `USER_ROLE` (
	`USER_ID` INT(11) NOT NULL,
	`ROLE_ID` INT(11) NOT NULL,
	PRIMARY KEY (`USER_ID`, `ROLE_ID`),
	INDEX `FK_it77eq964jhfqtu54081ebtio` (`ROLE_ID`),
	CONSTRAINT `FK_apcc8lxk2xnug8377fatvbn04` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_it77eq964jhfqtu54081ebtio` FOREIGN KEY (`ROLE_ID`) REFERENCES `RULE` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;

INSERT INTO `USER` (`ID`, `LOGIN`, `NAME`, `PASSWORD`) VALUES (1, 'teste1', 'teste1', '123');
INSERT INTO `USER` (`ID`, `LOGIN`, `NAME`, `PASSWORD`) VALUES (2, 'teste2', 'teste2', '123');
INSERT INTO `USER` (`ID`, `LOGIN`, `NAME`, `PASSWORD`) VALUES (3, 'teste3', 'teste3', '123');

INSERT INTO `ROLE` (`ID`, `NAME`) VALUES (1, 'ROLE_USER');
INSERT INTO `ROLE` (`ID`, `NAME`) VALUES (2, 'ROLE_ADMIN');
INSERT INTO `ROLE` (`ID`, `NAME`) VALUES (3, 'ROLE_GUEST');

INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (2, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (3, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1, 2);



