CREATE TABLE `USER` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`LOGIN` VARCHAR(255) NOT NULL,
	`NAME` VARCHAR(255) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `UK_587tdsv8u5cvheyo9i261xhry` (`LOGIN`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4;


CREATE TABLE `ROLE` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4;


CREATE TABLE `USER_ROLE` (
	`USER_ID` INT(11) NOT NULL,
	`ROLE_ID` INT(11) NOT NULL,
	PRIMARY KEY (`USER_ID`, `ROLE_ID`),
	INDEX `FK_it77eq964jhfqtu54081ebtio` (`ROLE_ID`),
	CONSTRAINT `FK_apcc8lxk2xnug8377fatvbn04` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
	CONSTRAINT `FK_it77eq964jhfqtu54081ebtio` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;





