INSERT INTO `USER` (`ID`, `LOGIN`, `NAME`, `PASSWORD`) VALUES (1, 'teste1', 'teste1', '123');
INSERT INTO `USER` (`ID`, `LOGIN`, `NAME`, `PASSWORD`) VALUES (2, 'teste2', 'teste2', '123');
INSERT INTO `USER` (`ID`, `LOGIN`, `NAME`, `PASSWORD`) VALUES (3, 'teste3', 'teste3', '123');

INSERT INTO `ROLE` (`ID`, `NAME`) VALUES (1, 'ROLE_USER');
INSERT INTO `ROLE` (`ID`, `NAME`) VALUES (2, 'ROLE_ADMIN');
INSERT INTO `ROLE` (`ID`, `NAME`) VALUES (3, 'ROLE_GUEST');

INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (2, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (3, 1);
INSERT INTO `USER_ROLE` (`USER_ID`, `ROLE_ID`) VALUES (1, 2);
