
CREATE DATABASE IF NOT EXISTS `controleacesso` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `controleacesso`;

CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  `SIGLA` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `SISTEMA` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIENT_ID` TEXT NULL,
  `NOME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(255) DEFAULT NULL,
  `PASSWORD` TEXT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USUARIO_ROLE` (
  `USUARIO_ID` bigint(20) NOT NULL,
  `ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`,`ROLE_ID`),
  KEY `FK_8d9yu0x4s0up5dpjfedk93k3w` (`ROLE_ID`),
  CONSTRAINT `FK_8d9yu0x4s0up5dpjfedk93k3w` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`),
  CONSTRAINT `FK_fjubv3kj7l38pg1m6frl0lum1` FOREIGN KEY (`USUARIO_ID`) REFERENCES `usuario` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USUARIO_SISTEMA` (
  `USUARIO_ID` bigint(20) NOT NULL,
  `SISTEMA_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`,`SISTEMA_ID`),
  KEY `FK_d7ocfx47jqt2p7t178e9wt5is` (`SISTEMA_ID`),
  CONSTRAINT `FK_d7ocfx47jqt2p7t178e9wt5is` FOREIGN KEY (`SISTEMA_ID`) REFERENCES `sistema` (`ID`),
  CONSTRAINT `FK_qvjb8e1i187r1iul970b9y7b0` FOREIGN KEY (`USUARIO_ID`) REFERENCES `usuario` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `ROLE` (`ID`, `NOME`, `SIGLA`) VALUES (1, 'Administrador', 'ADM');
INSERT INTO `SISTEMA` (`ID`, `CLIENT_ID`, `NOME`) VALUES (1, '646514d85279c63c7aacbc7a91e7575bd2d1adcb0086c45840242b090c69cc08', 'Cliente Web');
INSERT INTO `USUARIO` (`ID`, `NOME`, `PASSWORD`, `USER_NAME`) VALUES (1, 'Teste', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4', 'teste@teste.com');
INSERT INTO `USUARIO_ROLE` (`USUARIO_ID`, `ROLE_ID`) VALUES (1, 1);
INSERT INTO `USUARIO_SISTEMA` (`USUARIO_ID`, `SISTEMA_ID`) VALUES (1, 1);
