
ALTER TABLE `SISTEMA`
	CHANGE COLUMN `CLIENT_ID` `CLIENT_SECRET` TEXT NULL AFTER `ID`;

CREATE TABLE `ACESSO` (
	`TOKEN` TEXT NOT NULL,
	`REFRESH_TOKEN` TEXT NOT NULL,
	PRIMARY KEY (`TOKEN`(767))
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;