
ALTER TABLE `SISTEMA`
	CHANGE COLUMN `CLIENT_ID` `CLIENT_SECRET` TEXT NULL AFTER `ID`;

CREATE TABLE `ACESSO` (
	`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`TOKEN` TEXT NOT NULL,
	`REFRESH_TOKEN` TEXT NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;
